language: php

dist: bionic
sudo: false

git:
    depth: 1

php:
    - 7.3
    - 7.4

env:
    - ZABBIX_VERSION=3.0.0
    - ZABBIX_VERSION=3.4.15
    - ZABBIX_VERSION=4.0.0
    - ZABBIX_VERSION=4.4.4
    - ZABBIX_VERSION=5.0.0

jobs:
    fast_finish: true
    include:
        - php: 7.3
          dist: precise
          env: ZABBIX_VERSION=3.0.0
        - php: 7.3
          dist: precise
          env: ZABBIX_VERSION=3.4.15
        - php: 7.3
          dist: precise
          env: ZABBIX_VERSION=4.0.0
        - php: 7.3
          dist: precise
          env: ZABBIX_VERSION=4.4.4
        - php: 7.3
          dist: precise
          env: ZABBIX_VERSION=5.0.0

cache:
    directories:
        - $HOME/.composer

before_install:
    - |
      # General configuration
      stty cols 120
      mkdir -p /opt/zabbix
      wget -qO- https://repo.zabbix.com/zabbix/$(echo $ZABBIX_VERSION | cut -d. -f-2)/ubuntu/pool/main/z/zabbix/zabbix_$ZABBIX_VERSION.orig.tar.gz | tar xvz -C /opt/zabbix
      ln -s /opt/zabbix/zabbix-$ZABBIX_VERSION/frontends/php/ /opt/zabbix/frontend

install:
    - php ./src/build.php
    - composer install --prefer-dist --optimize-autoloader --classmap-authoritative --no-interaction --no-scripts

script:
    - ./vendor/bin/phpunit
    - ./vendor/bin/php-cs-fixer fix -v
