name: Quality assurance

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    phpstan:
        name: PHPStan

        runs-on: ubuntu-latest

        env:
            ZABBIX_VERSION: 3.0.0

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  coverage: none
                  tools: composer:v2

            - name: Install Composer dependencies (highest)
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "highest"
                  composer-options: "--prefer-dist --prefer-stable"

            - name: Get Zabbix source
              run: |
                mkdir -p /opt/zabbix
                wget -qO- https://repo.zabbix.com/zabbix/$(echo $ZABBIX_VERSION | cut -d. -f-2)/ubuntu/pool/main/z/zabbix/zabbix_$ZABBIX_VERSION.orig.tar.gz | tar xvz -C /opt/zabbix
                ln -s /opt/zabbix/zabbix-$ZABBIX_VERSION/frontends/php/ /opt/zabbix/frontend

            - name: Build
              run: src/build.php

            - name: PHPStan
              run: vendor/bin/phpstan --memory-limit=1G analyse
