name: Test

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        name: PHP ${{ matrix.php-version }} + Zabbix ${{ matrix.zabbix-version }}

        runs-on: ubuntu-latest

        continue-on-error: ${{ matrix.allowed-to-fail }}

        env:
            SYMFONY_REQUIRE: ${{matrix.symfony-require}}

        strategy:
            matrix:
                php-version:
                    - '7.3'
                    - '7.4'
                allowed-to-fail: [false]
                zabbix-version: ['3.0.0']
                include:
                    - php-version: '7.3'
                      zabbix-version: '3.0.0'
                      allowed-to-fail: false
                    - php-version: '7.3'
                      zabbix-version: '3.0.32'
                      allowed-to-fail: false
                    - php-version: '7.3'
                      zabbix-version: '3.2.0'
                      allowed-to-fail: false
                    - php-version: '7.3'
                      zabbix-version: '3.2.11'
                      allowed-to-fail: false
#                    - php-version: '7.3'
#                      zabbix-version: '5.0.0'
#                      allowed-to-fail: false

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Get Zabbix source
              run: |
                mkdir -p /opt/zabbix
                wget -qO- https://repo.zabbix.com/zabbix/$(echo ${{ matrix.zabbix-version }} | cut -d. -f-2)/ubuntu/pool/main/z/zabbix/zabbix_${{ matrix.zabbix-version }}.orig.tar.gz | tar xvz -C /opt/zabbix
                ln -s /opt/zabbix/zabbix-${{ matrix.zabbix-version }}/frontends/php/ /opt/zabbix/frontend

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: Add PHPUnit matcher
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: "Install Composer dependencies"
              uses: "ramsey/composer-install@v1"
              with:
                  composer-options: "--prefer-dist"

            - name: Build
              run: src/build.php

            - name: Run Tests
              run: vendor/bin/phpunit
